title: calculator
logo: https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRrEYFd_1iTEGnP1HmIgskow01-G74a-mUBX0th99V4Oixfi9q7
description: web based simple calculator
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
